<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TargetFramework>net10.0</TargetFramework>
    <UserSecretsId>0cba3cfb-8338-434f-a598-84eff1797a87</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.QuickGrid.EntityFrameworkAdapter" Version="10.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="NuGet.Protocol" Version="7.9.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Components\Pages\DirectionPages\" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="Components\Pages\GroupPages\Create.razor" />
    <_ContentIncludedByDefault Remove="Components\Pages\GroupPages\Delete.razor" />
    <_ContentIncludedByDefault Remove="Components\Pages\GroupPages\Details.razor" />
    <_ContentIncludedByDefault Remove="Components\Pages\GroupPages\Edit.razor" />
    <_ContentIncludedByDefault Remove="Components\Pages\GroupPages\Index.razor" />
  </ItemGroup>

</Project>
